### ISSUE TITLE
"Labels/status" menu is not triggered on Chrome Mobile&Desktop

### ISSUE THREAD

**Issue by softvision-oana-arbuzov** [webcompat/webcompat.com#2162]
URL: https://staging.webcompat.com/issues/1378
Browser / Version: Chrome Desktop 64.0.3282.167, Chrome Mobile 64.0.3282.137
Operating System: Google Pixel (Android 8.0.0) - 1080 x 1920 pixels (~441 ppi pixel density)

**Prerequisites:**
1. Github account available and signed in.

**Steps to Reproduce:**
1. Navigate to https://staging.webcompat.com/issues/1378
2. Scroll down the page to "Labels" and "Status" section.
3. Tap the "Edit" (labels/status) button. 

**Expected Behavior:**
Menu with all available labels/status is displayed.

**Actual Behavior:**
Nothing happens, menu is not triggered.

**Note**
1. Not reproducible on Firefox Mobile & Desktop.
2. Affected area:
```html
<button class="nav-button nav-link icon right js-CategoryEditorLauncher js-LabelEditorLauncher">
	<svg class="nav-text icon nav-icon" viewBox="0 0 30 30" role="presentation">
		<title>Edit labels</title>
		<use href="#svg-sliders">Edit labels</use>
	</svg>
</button>
<!--not needed-->
<svg class="nav-text icon nav-icon" viewBox="0 0 30 30" role="presentation">
	<title>Edit labels</title>
	<use href="#svg-sliders">Edit labels</use>
</svg>
```

Watchers:
@softvision-sergiulogigan
@softvision-oana-arbuzov

![editbtn_notworkingchrome](https://user-images.githubusercontent.com/12184325/36382980-6cf428fc-1593-11e8-9ba0-66ad57eeb3a6.gif)

**Comment by zoepage** [comment]
The positioning for the other breaking points are missing. This needs fixing. Thanks for reporting. :)

**Comment by miketaylr** [comment]
I think I fixed this in https://github.com/webcompat/webcompat.com/commit/879252723e42d25bc3f60d1c15efca6cc82e5611, let's re-test once we deploy from refactor branch again.

**Comment by magsout** [comment]
I'm not able to reproduce. I agree with @miketaylr .

**Comment by miketaylr** [comment]
> I'm not able to reproduce. I agree with @miketaylr .

Yep, I just retested and it works as expected (but the layout is wrong... possibly tracked in another issue?)

![screenshot_20180316-164235](https://user-images.githubusercontent.com/67283/37546038-1b5bb668-2939-11e8-84bf-9d5bba6d7756.png)

@softvision-oana-arbuzov can you verify this works now?

**Comment by magsout** [comment]
@miketaylr the layout is fixed with this PR https://github.com/webcompat/webcompat.com/pull/2133

**Comment by zoepage** [comment]
🎉

**Comment by softvision-oana-arbuzov** [comment]
@miketaylr, it is still reproducible for me, maybe the fix is not yet available in the current version of staging.webcompat.com. Now it is also reproducible on Firefox Nightly

**Tested with:**
Browser / Version: Firefox Nightly 61.0a1 (2018-03-18), Chrome Mobile 65.0.3325.109
Operating System: Google Pixel (Android 8.0.0) - 1080 x 1920 pixels (~441 ppi pixel density)

**Comment by zoepage** [comment]
I can also reproduce... :/

**Comment by miketaylr** [comment]
> I can also reproduce... :/

@zoepage what device?

**Comment by miketaylr** [comment]
@softvision-oana-arbuzov I also have a pixel on Android 8. Strange we get different results.

**Comment by zoepage** [comment]
@miketaylr a Pixel. 
Probably a caching issue as I can't reproduce anymore and have a different bug now described in #2262.

**Comment by miketaylr** [comment]
> I can't reproduce anymore

OK, let's go ahead and close this and try to fix #2262...

**Comment by softvision-oana-arbuzov** [comment]
Strangely I can still reproduce it both on mobile devices and on Responsive design mode, even after clearing cache.

**Comment by softvision-sergiulogigan** [comment]
I'm also reproducing this on Huawei P10, Android 7.0 and Nightly 61.
Tried both before and after Clear App Data (from Android Settings).

![image](https://user-images.githubusercontent.com/16573771/37699900-3ca4516a-2cf2-11e8-9e5a-f45fc0c561af.png)

**Comment by Regaddi** [comment]
I guess the fix hasn't been deployed on staging yet.

**Comment by zoepage** [comment]
No, it hasn't. Will probably be on Friday.
