### ISSUE TITLE
Intermittent Travis failures

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#2375]
See https://travis-ci.org/webcompat/webcompat.com/builds/364187331#L1039

<img width="959" alt="screen shot 2018-04-09 at 1 26 39 pm" src="https://user-images.githubusercontent.com/67283/38515383-a84d67d8-3bf9-11e8-9141-93d210bebd81.png">

https://github.com/webcompat/webcompat.com/blob/8203b7a482cbb78fabb5a458e8565227d15acebd/tests/functional/lib/setup.js#L21

Possibly there's a timing issue here? I wonder if we can just throw in a timeout here. I'd like to add some diagnostic logging to understand the error first, right now we just swallow it.

**Comment by zoepage** [comment]
Re-opening as #2385 is "just" adding diagnostics, but not a solution yet.

**Comment by miketaylr** [comment]
Still intermittents... and it seems like logging from #2385 hasn't turned up anything useful yet.

https://travis-ci.org/webcompat/webcompat.com/builds/368261531

**Comment by karlcow** [comment]
pet theory when looking at the #2492 Pull request.


This error message identical to the one created by travis is simple to generate:

```
 node ./tests/functional/_intern.js "--reporters=runner"
Error: 
        ======================================================
        Oops, something went wrong. Try restarting the server.
        Open another terminal and window type:
        npm run start:test
        or
        python run.py -t
        ======================================================
        
  at ClientRequest.<anonymous>  <tests/functional/lib/setup.js:55:9>
  at ClientRequest.emit  <events.js:180:13>
  at Socket.socketErrorListener  <_http_client.js:395:9>
  at Socket.emit  <events.js:180:13>
  at emitErrorNT  <internal/streams/destroy.js:64:8>
{ Error: 
        ======================================================
        Oops, something went wrong. Try restarting the server.
        Open another terminal and window type:
        npm run start:test
        or
        python run.py -t
        ======================================================
        
    at ClientRequest.<anonymous> (/Users/karl/code/webcompat.com/tests/functional/lib/setup.js:55:9)
    at ClientRequest.emit (events.js:180:13)
    at Socket.socketErrorListener (_http_client.js:395:9)
    at Socket.emit (events.js:180:13)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at process._tickCallback (internal/process/next_tick.js:114:19) reported: true }
```

This happens when I start `node ./tests/functional/_intern.js "--reporters=runner"`
without starting the python server.


## Theory
The python server takes a bit of time to start because of the milestones dance. If the tests are starting before the milestones are initialized it will fail.

**Comment by zoepage** [comment]
fixed #2492

**Comment by karlcow** [comment]
@zoepage My understanding is that @miketaylr said that it is not fixed yet. See the comment 
in https://github.com/webcompat/webcompat.com/pull/2492#issuecomment-395845322

**Comment by zoepage** [comment]
Sorry, I've misunderstood the comment! :)

**Comment by miketaylr** [comment]
> The python server takes a bit of time to start because of the milestones dance. If the tests are starting before the milestones are initialized it will fail.

ooooo

**Comment by miketaylr** [comment]
Got one: https://github.com/webcompat/webcompat.com/pull/2502#issuecomment-398188628

`something bad happened inside intern.run()`

**Comment by softvision-oana-arbuzov** [comment]
We did reproduce the issue for PRs #2500 and #2499.
