### ISSUE TITLE
Update Webcompat.com SSL Certificate

### ISSUE THREAD

**Issue by reinhart1010** [webcompat/webcompat.com#2780]
Recently visited webcompat.com today and found that the SSL certificate is expired.

![screenshot_20190127-131045_firefox](https://user-images.githubusercontent.com/17312341/51797378-215f1000-2235-11e9-9fbc-4f9980c0e064.jpg)

SeeAlso: @webcompat/web-bugs#24893

**Comment by R-Adrian** [comment]
also seeing this.
what happened to the automated renewal cron job that was supposed to be scheduled?

crt.sh shows that the certificate was not renewed at all, only the staging website had a renewal on 2018-12-14, but not the main sites.

**Comment by karlcow** [comment]
huh. @miketaylr might know.

**Comment by karlcow** [comment]
Though. This morning. With Firefox Nightly 66.0a1 (2019-01-27) (64-bit)

<img width="700" alt="capture d ecran 2019-01-28 a 08 10 13" src="https://user-images.githubusercontent.com/505230/51808198-2921c180-22d4-11e9-87b1-dc5ac3c8af43.png">

and 

<img width="700" alt="capture d ecran 2019-01-28 a 08 10 41" src="https://user-images.githubusercontent.com/505230/51808205-3c349180-22d4-11e9-8940-6898a2adb04d.png">

**Comment by reinhart1010** [comment]
I can also see this is working now. Closing as fixed.

**Comment by karlcow** [comment]
I have the feeling this is is fixed. Maybe it was just bad timing.

**Comment by miketaylr** [comment]
Thanks for the report all!

**Comment by R-Adrian** [comment]
https://crt.sh/?q=%webcompat.com
shows that the certificate was only issued for https://webcompat.com/  (no www)

https://www.webcompat.com/ is STILL broken because it was not specified as alternate name.

**Comment by softvision-sergiulogigan** [comment]
Let's reopen this, as www.webcompat.com is still not working due to certificates issues.

**Comment by miketaylr** [comment]
Oh, I guess if google points to www, this is a lot more important.

**Comment by miketaylr** [comment]
Thanks to @denschub's server-fu, we've fixed the www redirect to non-www and use the same cert for both (so the redirect actually works).

(And we fixed a bug in the renewal).
